### ISSUE TITLE
com.cleverpush.banner.WebViewActivity.init: java.lang.NullPointerException - Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference

### ISSUE THREAD

**Issue by neronovs** [cleverpush/cleverpush-flutter-sdk#57]
**Environment:
Flutter CleverPush SDK 1.23.24
Platform: Android only (OS versions 8.0 till 14.0), iOS - no issue**

In the FB Crashlytics we detected massive crashes, related to the CleverPush SDK.

Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{de.apodiscounter.androidphone/com.cleverpush.banner.WebViewActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference

**Stacktrace:**
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
       at com.cleverpush.banner.WebViewActivity.init(:34)
       at com.cleverpush.banner.WebViewActivity.handleBundleData(:14)
       at com.cleverpush.banner.WebViewActivity.onCreate(:16)
       at android.app.Activity.performCreate(Activity.java:8891)
       at android.app.Activity.performCreate(Activity.java:8856)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1468)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3973)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4144)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:224)
       at android.os.Looper.loop(Looper.java:318)
       at android.app.ActivityThread.main(ActivityThread.java:8759)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
    
It would be very helpful, if you could help to solve the issue.

**Comment by gbhrdt** [comment]
Hi @neronovs  thanks for bringing that up!
We just released our Flutter SDK version `1.23.26` which will prevent this crash. Could you test with it? 👍
