### ISSUE TITLE
Android java.lang.NullPointerException: Attempt to invoke virtual method

### ISSUE THREAD

**Issue by cschellhas** [cleverpush/cleverpush-flutter-sdk#6]
Hi now getting error on Android if I try to open Topics Dialog

**Code to open Topics:**
```
  showTopic() {
    CleverPush.shared.showTopicsDialog();
  }
```

**Error:**

```
E/MethodChannel#CleverPush(17576): Failed to handle method call
E/MethodChannel#CleverPush(17576): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
E/MethodChannel#CleverPush(17576): 	at com.cleverpush.CleverPush.lambda$showTopicsDialog$32$CleverPush(CleverPush.java:1630)
E/MethodChannel#CleverPush(17576): 	at com.cleverpush.-$$Lambda$CleverPush$dSVOqsZ1EPZIQ44oSdQ3vBhW_ww.ready(Unknown Source:8)
E/MethodChannel#CleverPush(17576): 	at com.cleverpush.CleverPush.getChannelConfig(CleverPush.java:871)
E/MethodChannel#CleverPush(17576): 	at com.cleverpush.CleverPush.showTopicsDialog(CleverPush.java:1595)
E/MethodChannel#CleverPush(17576): 	at com.cleverpush.CleverPush.showTopicsDialog(CleverPush.java:1590)
E/MethodChannel#CleverPush(17576): 	at com.cleverpush.CleverPush.showTopicsDialog(CleverPush.java:1586)
E/MethodChannel#CleverPush(17576): 	at com.cleverpush.flutter.CleverPushPlugin.showTopicsDialog(CleverPushPlugin.java:114)
E/MethodChannel#CleverPush(17576): 	at com.cleverpush.flutter.CleverPushPlugin.onMethodCall(CleverPushPlugin.java:58)
E/MethodChannel#CleverPush(17576): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#CleverPush(17576): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#CleverPush(17576): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#CleverPush(17576): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#CleverPush(17576): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#CleverPush(17576): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#CleverPush(17576): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#CleverPush(17576): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#CleverPush(17576): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#CleverPush(17576): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter (17576): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference, null)
E/flutter (17576): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (17576): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (17576): <asynchronous suspension>
E/flutter (17576): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (17576): #3      CleverPush.showTopicsDialog (package:cleverpush_flutter/cleverpush_flutter.dart:56:27)
E/flutter (17576): #4      EinstellungenModel.showTopic (package:Kinzig.News/ui/views/einstellungen/einstellungenModel.dart:95:23)
E/flutter (17576): #5      EinstellungenView.build.<anonymous closure>.<anonymous closure> (package:Kinzig.News/ui/views/einstellungen/einstellungenView.dart:69:56)
E/flutter (17576): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (17576): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (17576): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (17576): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (17576): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (17576): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter (17576): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter (17576): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (17576): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (17576): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (17576): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (17576): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (17576): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (17576): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (17576): #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (17576): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (17576): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (17576): #23     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (17576): #24     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (17576): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (17576): #26     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (17576): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
```

It happens only after Start. If I suspend App to background and then back to foreground the same Button works.

Greetings

**Comment by gbhrdt** [comment]
Hi @cschellhas  could you show me how you initialized the plugin?
Does this problem also occur in our example project? I justed tested with the example project (https://github.com/cleverpush/cleverpush-flutter-sdk/blob/master/example/lib/main.dart) and it works without any problem (there is a "Show topics dialog" button).

**Comment by cschellhas** [comment]
Init Process:


```
initialise() {
    //Setup Cleverpush
    initCleverPush();
  }

  Future<void> initCleverPush() async {
    await CleverPush.shared.init("XsBhXJd9NLX4ErJuP");
    getNotificationPermStatus();
  }

  /// Checks the notification permission status
  Future getNotificationPermStatus() async {
    NotificationPermissions.getNotificationPermissionStatus().then((status) {
      SharedPreferences.getInstance().then((SharedPreferences sp) {
        bool notificationEnabled = sp.getBool('notification');

        CleverPush.shared.isSubscribed().then((status) {
          print('Status is --> ' + status.toString());
          notificationEnabled = status;
          switchOn = status;
        });

        // will be null if never previously saved
        if (notificationEnabled == false) {
          switchOn = false;
        } else {
          switchOn = true;
        }
        notifyListeners();
      });

      switch (status) {
        case PermissionStatus.denied:
          notificationActive = false;
          return 'notificationInactive';
        case PermissionStatus.granted:
          notificationActive = true;
          return 'notificationActive';
        case PermissionStatus.unknown:
          return 'notificationActive';
      }
      return 'unknown';
    });
  }
```

show Topic via

```
  showTopic() {
    CleverPush.shared.showTopicsDialog();
  }
```

And Log says

```
I/flutter (18752): CleverPush: Flutter initializing
D/CleverPush(18752): Initializing with Channel ID: ******* (SDK 1.3.0)
D/CleverPush(18752): Subscribed with ID (next sync at 2020-08-08 07:56:43 GMT+02:00): Bcejzon5cfDTvXMPo
I/flutter (18752): CleverPush: _handleMethod: CleverPush#handleSubscribed
I/flutter (18752): _InternalLinkedHashMap<dynamic, dynamic>
D/EGL_emulation(18752): eglMakeCurrent: 0xdd81aa80: ver 3 0 (tinfo 0xdd80fb70)
I/flutter (18752): Status is --> true
E/MethodChannel#CleverPush(18752): Failed to handle method call
E/MethodChannel#CleverPush(18752): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
```
java.lang.NullPointerException fires after the button click.


After suspending App to background and then to foreground the same Button works and the Dialog show up.

`D/CleverPush(18752): showTopicsDialog activity: de.kinzignews.kinzignews.MainActivity`

**Comment by gbhrdt** [comment]
@cschellhas  Thanks ! Could you please try the just releases Version 1.2.2?
